# Generated by Django 2.1.5 on 2020-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20201123_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombres',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
    ]
