# Generated by Django 2.1.5 on 2020-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20201123_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(default='M', max_length=1, verbose_name='Genero'),
        ),
    ]
